# Numpy
* NumPy is a Python library.
* NumPy is used for working with arrays.
* NumPy is short for "Numerical Python" and it is represented as np

## Importing Numpy

In [1]:
import numpy as np

## Numpy Version

In [2]:
print(np.__version__)

1.19.5


## Creating Numpy array 
#### Using list

In [3]:
arr1=np.array([5,6,7,8,9])
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[5 6 7 8 9]


 #### Using tuple

In [4]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### Using set 

In [5]:
s1={1,2,3,4,5,6}
arr3=np.array(s1)
print(arr3)
print(type(arr3))

{1, 2, 3, 4, 5, 6}
<class 'numpy.ndarray'>


## Creating an array using arange

In [6]:
#create array using arange
arr4=np.arange(10)
print(arr4)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr4=np.arange(2,10)
print(arr4)

[2 3 4 5 6 7 8 9]


In [8]:
arr4=np.arange(0,10,2) #start point-end point-step-size
print(arr4)

[0 2 4 6 8]


## Creating array using linspace

In [9]:
#crate 1-darray using linspace function
arr4= np.linspace(0,5,1)
print(arr4)

[0.]


In [10]:
arr4= np.linspace(0,5,20)
print(arr4)

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


In [11]:
arr4= np.linspace(0,5,20)
print(arr4)
print("array dimension:",arr4.ndim)
print("array shape:",arr4.shape)
print("dat type of array:",arr4.dtype)

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
array dimension: 1
array shape: (20,)
dat type of array: float64


## Dimensions in arrays
#### Zero-Dimensions

In [12]:
arr4=np.array(56)
print(arr4)
print(type(arr4))

56
<class 'numpy.ndarray'>


#### One-Dimensions

In [13]:
arr5=np.array([1,2,3,4,5])
print(arr5)

[1 2 3 4 5]


#### Two-Dimensions

In [14]:
arr6=np.array([[1,2,3,4],[5,6,7,8]])
print(arr6)

[[1 2 3 4]
 [5 6 7 8]]


#### Three-Dimensions

In [15]:
arr7=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr7)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
arr8=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[0,1,2,3]])
print(arr8)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 0  1  2  3]]


## Check the number of dimensions

In [17]:
arr4=np.array(56)
arr5=np.array([1,2,3,4,5])
arr6=np.array([[1,2,3,4],[5,6,7,8]])
arr7=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr8=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr4.ndim)
print(arr5.ndim)
print(arr6.ndim)
print(arr7.ndim)
print(arr8.ndim)

0
1
2
2
3


### Array with 5 dimensions

In [18]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Array indexing

In [19]:
arr5=np.array([1,2,3,4,5])
print(arr5[0])

1


In [20]:
print(arr5[-1])

5


In [21]:
print(arr5[0:])

[1 2 3 4 5]


In [22]:
print(arr5[:])

[1 2 3 4 5]


In [23]:
print(arr5[1:3])

[2 3]


In [24]:
print(arr5[1]+arr5[[4]])          #2+5=7

[7]


## Accessing 2-D array

In [25]:
arr6=np.array([[1,2,3,4],[5,6,7,8]])
print("Second element in the first row:" ,arr6[0,1])

Second element in the first row: 2


In [26]:
print("3rd element in the second row:" ,arr6[1,3])

3rd element in the second row: 8


## Accessing 3-D array

In [27]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


* And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

## Numpy array slicing
* Slicing in python means taking elements from one given index to another given index.
* We pass slice instead of index like this: [start:end].
* We can also define the step, like this: [start:end:step].

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [30]:
print(arr[4:])

[5 6 7]


In [31]:
print(arr[::2])

[1 3 5 7]


## Slicing 2-D array

In [32]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [33]:
print(arr[0,2:4])

[3 4]


In [34]:
print(arr[0:2, 2])

[3 8]


In [35]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# Data types in Numpy
Below is a list of all data types in NumPy and the characters used to represent them.

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

### Checking the type of array

In [36]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [37]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [38]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## Copy vs View

In [39]:
arr = np.array([1, 2, 3, 4, 5])          ##copy
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [40]:
arr = np.array([1, 2, 3, 4, 5])                  ##view
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


## Shape of an array

In [41]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [42]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


## Reshaping of an array

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [45]:
# 1-D to 2-D conversion

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [46]:
## 1-D to 3-D conversion
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Flattering array
* Flattening array means converting a multidimensional array into a 1D array.

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


## Iterating array
* Iterating means going through elements one by one.

In [48]:
arr = np.array([1, 2, 3])
for x in arr:                                       ##iterating 1-D array
  print(x)

1
2
3


In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:                                  ##iterating 2-D array
  print(x)

[1 2 3]
[4 5 6]


In [50]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:                                        ### iterating 3-D array
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## Array join

In [51]:
arr1 = np.array([1, 2, 3])                                 ## 1-D array
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [52]:
arr1 = np.array([[1, 2], [3, 4]])                                ##2-D array
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [53]:
arr1 = np.array([1, 2, 3])                            ###Array join using stack
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [54]:
arr1 = np.array([1, 2, 3])                            ## Stacking along rows
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [55]:
arr1 = np.array([1, 2, 3])                      ### stacking along column 
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [56]:
arr1 = np.array([1, 2, 3])                             ##stacking along height(depth)
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## Splitting array
#### 1-D

In [57]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)                             ##into 3 parts
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)                            ##into 4 parts
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Splitting 2-D

In [59]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


## Searching arrays

In [60]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)                                     ##Which means that the value 4 is present at index 3, 5, and 6.

(array([3, 5, 6], dtype=int64),)


In [61]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


## Sorting arrays

In [62]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [63]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [64]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Filtering array

In [65]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


# Numpy Random

In [66]:
#creating random array
arr5=np.random.rand(5)              ##it will chnage the values for every run
print(arr5)

[0.55327255 0.4039502  0.99277934 0.55851562 0.23558472]


In [67]:
#create random array of integers
arr6=np.random.randint(0,5)      #we will get different value because of processors we used.
print(arr6)

0


In [68]:
arr6=np.random.randint(0,50,10)    #random nmbers---(start,stop,stepsize)
print(arr6)

[27  0 38 39 10 46 44 15 21 14]


In [70]:
#create random array of  integers using random_integers()
arr6=np.random.random_integers(0,50,10)    #random nmbers
print(arr6)

### We will get warning while using random_integers() is due to out dated version  

[19 22 18 39 41 34  1 29 28 12]


<ipython-input-70-f7974e666c9c>:2: DeprecationWarning: This function is deprecated. Please call randint(0, 50 + 1) instead
  arr6=np.random.random_integers(0,50,10)    #random nmbers


In [71]:
import warnings  #we will not get warning
warnings.filterwarnings('ignore')
arr7= np.random.random_integers(0,50,20)
print(arr7)
#by importing warnings we can avoid the warnings

[ 3  9 41 34  0 46 19 29 26 47 34 18 27 47 33  8  8  5 35 20]


In [72]:
#create array of normally distributes
arr8=np.random.randn(50)
print(arr8)

[ 0.68675532 -0.56059328  1.23547593 -0.0195842  -0.11417774  0.7754684
 -1.17890374  0.02709373  0.47857927  0.50099385  0.22800971 -0.16308735
 -0.50674995 -0.45509013  0.93982166  0.37683579  0.3703049  -1.21672364
  1.17594032  0.43741154  0.10921867  1.07833042  1.00119024 -0.44890445
 -1.12375433 -0.49266403 -0.01246146 -0.40921675  0.95891629  0.38020253
  1.52111344  1.71725085 -0.23786346  0.38265597  0.58446586 -1.0200663
 -0.56742646 -0.44115181  1.42129042  0.95888239 -2.02553661  0.19256912
 -1.8319775  -0.51102095  1.27682772 -0.77062405 -1.92653036 -0.16507538
  0.07114665 -0.27287638]
