####

# 🐍 NumPy Tutorial – Mastering Arrays in Python

## 1. What is a NumPy Array?

NumPy is a Python library. NumPy (Numerical Python) is the **fundamental package for scientific computing in Python**. Its main feature is the **`ndarray` (n-dimensional array)**, a powerful object that allows you to store and manipulate **large datasets efficiently**.

🔹 Why use NumPy arrays instead of Python lists?

* Lists are flexible but **slow** for mathematical operations.
* NumPy arrays are **faster, more memory-efficient**, and support **vectorized operations** (performing operations on entire arrays without loops).
* Essential for **data science, AI, ML, and image processing**.


# 📘 NumPy Tutorial Roadmap

Let’s now go step by step through the essential topics:

---

## 2. NumPy HOME

Think of this as the **landing page** for NumPy. It tells us NumPy is:

* Open-source
* Used for numerical data
* Supports arrays, matrices, random numbers, and linear algebra

---

## 3. NumPy Intro

* NumPy was created in 2005 by Travis Oliphant.
* Built on **C and Fortran**, making it **super fast**.
* Used in data science libraries like Pandas, TensorFlow, and SciPy.

## 4. NumPy Getting Started

To install NumPy:

```bash
pip install numpy
```

To use it:


In [1]:
#pip install numpy

In [2]:
import numpy as np

## Numpy Version

In [3]:
print(np.__version__)

1.26.3


In [4]:
## example

# Python list
list1 = [1, 2, 3, 4, 5]

# NumPy array
arr = np.array([1, 2, 3, 4, 5])

print(list1)   # [1, 2, 3, 4, 5]
print(arr)     # [1 2 3 4 5]

# Array operations
print(arr * 2)  # [ 2  4  6  8 10]


[1, 2, 3, 4, 5]
[1 2 3 4 5]
[ 2  4  6  8 10]


#### 👉 Notice how multiplying the list by 2 just repeats it, but multiplying the array by 2 scales all elements.

## Why NumPy arrays are better than Python lists with a performance example.

In [5]:
import numpy as np
import time

# Python list
list1 = list(range(1, 1000000))
start = time.time()
list_sum = [x*2 for x in list1]
print("Python list time:", time.time() - start)

# NumPy array
arr = np.arange(1, 1000000)
start = time.time()
arr_sum = arr * 2
print("NumPy array time:", time.time() - start)


Python list time: 0.6635754108428955
NumPy array time: 0.01495361328125


## 5. NumPy Creating Arrays
#### Using list

In [6]:
arr1=np.array([5,6,7,8,9])
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[5 6 7 8 9]


 #### Using tuple

In [7]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### Using set 

In [8]:
s1={1,2,3,4,5,6}
arr3=np.array(s1)
print(arr3)
print(type(arr3))

{1, 2, 3, 4, 5, 6}
<class 'numpy.ndarray'>


## Creating an array using arange

In [9]:
#create array using arange
arr4=np.arange(10)
print(arr4)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
arr4=np.arange(2,10)
print(arr4)

[2 3 4 5 6 7 8 9]


In [11]:
arr4=np.arange(0,10,2) #start point-end point-step-size
print(arr4)

[0 2 4 6 8]


## Creating array using linspace

In [12]:
#crate 1-darray using linspace function
arr4= np.linspace(0,5,1)
print(arr4)

[0.]


In [13]:
arr4= np.linspace(0,5,20)
print(arr4)

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


In [14]:
arr4= np.linspace(0,5,20)
print(arr4)
print("array dimension:",arr4.ndim)
print("array shape:",arr4.shape)
print("dat type of array:",arr4.dtype)

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
array dimension: 1
array shape: (20,)
dat type of array: float64


### Other ways to create arrays:

In [15]:
# From a Python list
arr1 = np.array([1, 2, 3])

In [16]:
# Zeros and ones
arr2 = np.zeros((2, 3))    # 2x3 array of zeros
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr3 = np.ones((2, 2))     # 2x2 array of ones
arr3

array([[1., 1.],
       [1., 1.]])

In [18]:
arr6 = np.eye(3) #identity

print(arr6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Dimensions in arrays
#### Zero-Dimensions

In [19]:
arr4=np.array(56)
print(arr4)
print(type(arr4))

56
<class 'numpy.ndarray'>


#### One-Dimensions

In [20]:
arr5=np.array([1,2,3,4,5])
print(arr5)

[1 2 3 4 5]


#### Two-Dimensions

In [21]:
arr6=np.array([[1,2,3,4],[5,6,7,8]])
print(arr6)

[[1 2 3 4]
 [5 6 7 8]]


#### Three-Dimensions

In [22]:
arr7=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr7)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr8=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[0,1,2,3]])
print(arr8)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 0  1  2  3]]


## ndarray attributes (commonly used in practice):

In [24]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)     # Number of dimensions
print(arr.shape)    # Shape of array
print(arr.size)     # Total number of elements
print(arr.itemsize) # Bytes per element
print(arr.nbytes)   # Total memory used

2
(2, 3)
6
4
24


## Check the number of dimensions

In [25]:
arr4=np.array(56)
arr5=np.array([1,2,3,4,5])
arr6=np.array([[1,2,3,4],[5,6,7,8]])
arr7=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr8=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr4.ndim)
print(arr5.ndim)
print(arr6.ndim)
print(arr7.ndim)
print(arr8.ndim)

0
1
2
2
3


### Array with 5 dimensions

In [26]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## 6. NumPy Array Indexing

In [27]:
arr5=np.array([1,2,3,4,5])
print(arr5[0])

1


In [28]:
print(arr5[-1])

5


In [29]:
print(arr5[0:])

[1 2 3 4 5]


In [30]:
print(arr5[:])

[1 2 3 4 5]


In [31]:
print(arr5[1:3])

[2 3]


In [32]:
print(arr5[1]+arr5[[4]])          #2+5=7

[7]


In [33]:
arr = np.array([10, 20, 30, 40])
print(arr[0])   # 10
print(arr[-1])  # 40

10
40


## Accessing 2-D array

In [34]:
arr6=np.array([[1,2,3,4],[5,6,7,8]])
print("Second element in the first row:" ,arr6[0,1])

Second element in the first row: 2


In [35]:
print("3rd element in the second row:" ,arr6[1,3])

3rd element in the second row: 8


## Accessing 3-D array

In [36]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


* And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

## 7. NumPy Array Slicing

* Slicing in python means taking elements from one given index to another given index.
* We pass slice instead of index like this: [start:end].
* We can also define the step, like this: [start:end:step].

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [39]:
print(arr[4:])

[5 6 7]


In [40]:
print(arr[::2])

[1 3 5 7]


In [41]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])    # [20 30 40]
print(arr[:3])     # [10 20 30]
print(arr[::2])    # [10 30 50]

[20 30 40]
[10 20 30]
[10 30 50]


## Slicing 2-D array

In [42]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [43]:
print(arr[0,2:4])

[3 4]


In [44]:
print(arr[0:2, 2])

[3 8]


In [45]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## 8. NumPy Data Types
Below is a list of all data types in NumPy and the characters used to represent them.

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

### Checking the type of array

In [46]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [47]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [48]:
arr = np.array([1, 2, 3, 4], dtype='S')  ##assigning the type
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [49]:
arr = np.array([1, 2, 3], dtype='float')
print(arr.dtype)   # float64

float64


#### -  NumPy supports many types: `int32`, `float64`, `complex`, `bool`, etc.


In [50]:
arr = np.array([1.2, 2.3, 3.7])
print(arr.astype(int))

[1 2 3]


### What happens:

1. `arr` is initially of type `float64`.
2. `arr.astype(int)` creates a **new array** of integers.
3. Each element is **truncated toward zero**, so:

   * 1.2 → 1
   * 2.3 → 2
   * 3.4 → 3


#### It **does not round**. If you want rounding before conversion, you should use `np.round()` first:

In [51]:
np.round(arr).astype(int)  # [1 2 3] for this example, but [1.5, 2.7] would round properly

array([1, 2, 4])

## 9. NumPy Copy vs View

In [52]:
arr = np.array([1, 2, 3, 4, 5])          ##copy
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [53]:
arr = np.array([1, 2, 3, 4, 5])                  ##view
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [54]:
arr = np.array([1, 2, 3])
copy_arr = arr.copy()
view_arr = arr.view()

arr[0] = 99

print(copy_arr)   # [1 2 3] (not affected)
print(view_arr)   # [99 2 3] (affected)

[1 2 3]
[99  2  3]


## 10. NumPy Array Shape

In [55]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [56]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)   # (2, 3)

(2, 3)


## 11. NumPy Array Reshape

In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [59]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [60]:
# 1-D to 2-D conversion

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [61]:
## 1-D to 3-D conversion
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [62]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


### Transpose and Axis operations:

In [63]:

arr = np.array([[1,2,3],[4,5,6]])
print(arr.T)  # Transpose

# Sum along rows and columns
print(arr.sum(axis=0))  # column-wise sum
print(arr.sum(axis=1))  # row-wise sum

[[1 4]
 [2 5]
 [3 6]]
[5 7 9]
[ 6 15]


## Flattering array
* Flattening array means converting a multidimensional array into a 1D array.

In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


## 12. NumPy Array Iterating
* Iterating means going through elements one by one.

In [65]:
arr = np.array([1, 2, 3])
for x in arr:                                       ##iterating 1-D array
  print(x)

1
2
3


In [66]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:                                  ##iterating 2-D array
  print(x)

[1 2 3]
[4 5 6]


In [67]:
arr = np.array([[1, 2], [3, 4]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4


In [68]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:                                        ### iterating 3-D array
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


### Vectorized Operations (to contrast with loops):


In [69]:

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2)   # [5 7 9]
print(arr1 * arr2)   # [ 4 10 18]
print(arr1 ** 2)     # [1 4 9]

[5 7 9]
[ 4 10 18]
[1 4 9]


## 13. NumPy Array Join

In [70]:
arr1 = np.array([1, 2, 3])                                 ## 1-D array
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [71]:
a = np.array([1, 2])
b = np.array([3, 4])

joined = np.concatenate((a, b))
print(joined)   # [1 2 3 4]

[1 2 3 4]


In [72]:
arr1 = np.array([[1, 2], [3, 4]])                                ##2-D array
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [73]:
arr1 = np.array([1, 2, 3])                            ###Array join using stack
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [74]:
arr1 = np.array([1, 2, 3])                            ## Stacking along rows
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [75]:
arr1 = np.array([1, 2, 3])                      ### stacking along column 
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [76]:
arr1 = np.array([1, 2, 3])                             ##stacking along height(depth)
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## 14. NumPy Array Split
#### 1-D

In [77]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)                             ##into 3 parts
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [78]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)                            ##into 4 parts
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Splitting 2-D

In [79]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


## 15. NumPy Array Search

In [80]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)                                     ##Which means that the value 4 is present at index 3, 5, and 6.

(array([3, 5, 6], dtype=int64),)


In [81]:
arr = np.array([1, 2, 3, 4, 2, 2])
result = np.where(arr == 2)
print(result)   # (array([1, 4, 5]),)

(array([1, 4, 5], dtype=int64),)


In [82]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


### Boolean Indexing (super useful in ML/data science):

In [83]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])   # [30 40 50]


[30 40 50]


## 16. NumPy Array Sort

In [84]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [85]:
arr = np.array([3, 1, 4, 1, 5])
print(np.sort(arr))   # [1 1 3 4 5]

[1 1 3 4 5]


In [86]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [87]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## 17. NumPy Array Filter

In [88]:
arr = np.array([10, 15, 20, 25])
filter_arr = arr > 15
print(arr[filter_arr])   # [20 25]

[20 25]


In [89]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]



---

✨ **Summary of gaps to fill:**

1. Why NumPy (performance demo) – *at the start*
2. Array attributes (`shape`, `size`, `nbytes`) – *after dimensions*
3. Type conversion (`astype`) – *after data types*
4. Transpose & axis operations – *after reshape*
5. Vectorized operations – *after iterating*
6. Boolean indexing – *after searching*

---



####


# NumPy Array vs Python Array: What’s the Difference?

When working with numbers in Python, you’ll often see **NumPy arrays** and **Python arrays**. They might look similar, but they serve **different purposes**. Let’s explore the differences in a simple way.

---

## 1. Python’s Built-in `array` Module

Python’s standard library has an **`array`** module. Think of it as a **thin wrapper around C arrays**: lightweight and efficient, but basic.

### Key Features:

* Stores **only one data type** (all integers, or all floats, etc.)
* **More memory-efficient** than lists
* Provides **basic operations** only
* Ideal for **simple numeric storage** when advanced math isn’t needed


## 2. NumPy Arrays (`numpy.ndarray`)

**NumPy** is a third-party library that provides **powerful multi-dimensional arrays** (`ndarray`). These arrays are the backbone of **data science and scientific computing** in Python.

### Key Features:

* Supports **multi-dimensional arrays** (1D, 2D, 3D…)
* Optimized for **fast mathematical operations**
* Rich functionality: linear algebra, statistics, random numbers, broadcasting
* Widely used in **machine learning, AI, and data analysis**



---

## 3. Quick Comparison: Python Array vs NumPy Array

| Feature            | Python `array`         | NumPy `ndarray`                                          |
| ------------------ | ---------------------- | -------------------------------------------------------- |
| **Module**         | `array` (standard)     | `numpy` (external)                                       |
| **Dimensionality** | 1D only                | Multi-dimensional (1D, 2D, …)                            |
| **Data Types**     | Single type            | Homogeneous (with advanced types)                        |
| **Operations**     | Basic                  | Rich (linear algebra, stats, broadcasting)               |
| **Speed**          | Faster than list       | Highly optimized, much faster                            |
| **Use Case**       | Simple numeric storage | Data science, ML, image processing, scientific computing |

---

## 4. Which One Should You Use?

* Use **Python’s `array`** for **lightweight, simple 1D numeric storage**.
* Use **NumPy arrays** for **anything involving data analysis, ML, or numerical computations**.

💡 In practice, **NumPy arrays are the go-to choice** in almost all scientific and AI applications.


---

✅ **Summary:**

* **Python `array`** = simple, 1D, lightweight numeric container
* **NumPy `ndarray`** = powerful, multi-dimensional, optimized for scientific computing

---

##